SPKR_IDs=()

BASE_PATH=''
ORIGINAL_FILE_LIST_PATH='' # path to scp files

# fbank_or_plp
WAV_PATH='WAVE/'
PLP_SCP_PATH='PLP_SCP/'
PLP_PATH='PLP/'
FBK_SCP_PATH='FBK_SCP/'
FBK_PATH='FBK/'

FILE_LIST_PATH='TEMP/'
FILE_LIST_TIME_STAMP_PATH='STMP/'

# single_pass_retraining
PAIRED_SCP_FILE=''
MLF_FILE=''
ORIGINAL_HMM_FILE=''
RETRAINED_HMM_PATH=''
HMM_LIST_FILE=''