SPKR_IDs=()

BASE_PATH=''
ORIGINAL_FILE_LIST_PATH='' # path to scp files

WAV_PATH='WAVE/'
PLP_SCP_PATH='PLP_SCP/'
PLP_PATH='PLP/'
FBK_SCP_PATH='FBK_SCP/'
FBK_PATH='FBK/'

WAV_PATH='WAVE/'
PLP_SCP_PATH='PLP_SCP/'
FBK_SCP_PATH='FBK_SCP/'
PLP_PATH='PLP/'
FBK_PATH='FBK/'

FILE_LIST_PATH='TEMP/'
FILE_LIST_TIME_STAMP_PATH='STMP/'