BASE_PATH = '/project_bdda3/bdda/zrjin/Tempo_Generated/'
WAV_PATH = 'WAVE'
PLP_SCP_PATH = 'PLP_SCP'
FBK_SCP_PATH = 'FBK_SCP'
PLP_PATH = 'PLP'
FBK_PATH = 'FBK'

FEATURE_TYPE = 'fbk'

FILE_LIST_PATH = 'TEMP'
FILE_LIST_TIME_STAMP_PATH = 'STMP'